name: test & build package

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.event.repository.name }}
  cancel-in-progress: true

jobs:

  build:
    uses: cicd/workflows/.github/workflows/debian-package-build.yaml@master

    with:
      directory: pc-power-scheduler
      bypass-test-installation: true
